### ISSUE TITLE
404 page not found using router

### ISSUE THREAD

**Issue by beatscode** [go-humble/router#10]
I'm trying to build a very small example application to learn the framework. I'm thinking the below code (taken from router_test.go) is registering one handler. When it try the following url I get 404 errors. I'm running `gophers serve` in the directory

http://localhost:8080/com.home/testgopherjs/ - I don't get a 404 error here but I get the following in the console
`2016/12/21 21:25:54 Could not find route to match: /com.home/testgopherjs/     printToConsole — syscall.go:43`
http://localhost:8080/com.home/testgopherjs/greet/alex - returns 404
http://localhost:8080/com.home/testgopherjs/#/greet/alex - returns all coroutines are asleep

![46048756-aaf4-437f-9287-ccf6304a2839](https://cloud.githubusercontent.com/assets/1777648/21413667/0f11f4e6-c7c7-11e6-84c4-d09b4f6c791a.png)

How do I access the handler appropriately here?

```go
package main

import (
	"fmt"
	"github.com/go-humble/router"
)

func main() {
	// Create a new Router object
	r := router.New()
	// Use HandleFunc to add routes.
	r.HandleFunc("/greet/{name}", func(context *router.Context) {
		// The handler for this route simply grabs the name parameter
		// from the map of params and says hello.
		fmt.Printf("Hello, %s\n", context.Params["name"])
	})
	// You must call Start in order to start listening for changes
	// in the url and trigger the appropriate handler function.
	r.Start()
}
````

**Comment by albrow** [comment]
Firstly, I'm sorry for this poor example. The example code does work, but not without some additional code. I don't feel that the example code does a good job of explaining the context and would like to improve it.

> http://localhost:8080/com.home/testgopherjs/greet/alex - returns 404

This is because of the way the web works. When you type in that URL, your browser asks your server for the page at http://localhost:8080/com.home/testgopherjs/greet/alex and the server returns a 404 because it does not exist.

While [`History.pushState`](https://developer.mozilla.org/de/docs/Web/API/History) enables you to avoid using the `#` for routes in single page applications, you still have to start by visiting a URL that actually has the content you need. If you want URLs like this to work you will need to modify your server and either use server-side rendering (where the server renders the page on every first page load and then the client takes over after that) or a wild card route (where the server always returns the same content regardless of the URL and the client handles all routing and rendering). Again, this has nothing to do with GopherJS or go-humble/router and is just how browsers and web servers work.

> http://localhost:8080/com.home/testgopherjs/#/greet/alex - returns all coroutines are asleep

I'm not exactly sure why the `all goroutines asleep` error is coming up, but the reason this route does not work is that by default, go-humble/router will detect whether the History API is supported and use it instead of hash-based URLS (i.e. "the hash trick") if it is. If you are using a browser which supports the History API, routes like this will not work by default.

You can either change your server so that regular URLs are supported (either with server-side rendering or wild-card routing) or simply force the router to use the hash trick. Here is what the latter would look like:

```go
package main

import (
	"fmt"

	"github.com/go-humble/router"
)

func main() {
	// Create a new Router object
	r := router.New()
	// Force the router to use hash-based URLs for the purposes of
	// this example. Usually you want the default behavior of using
	// the History API if available.
	r.ForceHashURL = true
	// Use HandleFunc to add routes.
	r.HandleFunc("/greet/{name}", func(context *router.Context) {
		// The handler for this route simply grabs the name parameter
		// from the map of params and says hello.
		fmt.Printf("Hello, %s\n", context.Params["name"])
	})
	// You must call Start in order to start listening for changes
	// in the url and trigger the appropriate handler function.
	r.Start()
}

```

I have just tested this example locally and it works for me.

**Comment by albrow** [comment]
@beatscode hopefully this helped you resolve your issue. I'm going to close this since it's been a while.
